name: space_road
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flame: ^1.10.0
  flame_forge2d: ^0.15.1
  google_fonts: ^6.1.0
  sensors_plus: ^3.0.3
  flame_gdx_texture_packer: ^0.6.1
  shared_preferences: ^2.2.2
  flame_audio: ^2.1.3

flutter:
  uses-material-design: true
  fonts:
    - family: Quinque
      fonts:
        - asset: fonts/QuinqueFive.ttf
          style: normal
          weight: 400

  assets:
    - assets/images/
    # - assets/images/coin/
    # - assets/images/robot/
    - assets/
    - assets/images/explosion/
    - assets/audio/bgm.mp3
    - assets/audio/click.mp3
    - assets/audio/fail.mp3